config/routes.rb
Rails.application.routes.draw do

  # get '/', to: 'sessions#welcome'
  root to: 'sessions#welcome'
  
  resources :users do
    resources :flashcards, only: [:show, :idex, :new]
    get 'users_flashcards', to: "flashcards#users_flashcards"
  end
  # get 'users/:id/user_flashcards' => 'user#user_flashcards'

  resources :flashcards 

  resources :subjects

  resources :sessions
  get '/login', to: 'sessions#login'
  post 'login', to: 'sessions#create'
  delete "logout", to: 'sessions#destroy'

  get "/auth/:provider/callback" => 'sessions#omniauth'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flashcard.rb
class Flashcard < ApplicationRecord
    belongs_to :user
    has_many :flashcard_subjects
    has_many :subjects, through: :flashcard_subjects

    accepts_nested_attributes_for :flashcard_subjects
    

    validates :question, presence: true
    validates :answer, presence: true

    scope :public_card, -> { where(status: true) }
    

end

app/models/flashcard_subject.rb
class FlashcardSubject < ApplicationRecord
    belongs_to :subject
    belongs_to :flashcard 
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :flashcard_subjects
    has_many :flashcards, through: :flashcard_subjects

    validates :name, presence: true
    validates :name, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
    
    has_many :flashcards
    
    has_secure_password
    validates :name, presence: true
    validates :email, presence: true
    validates :email, uniqueness: { case_sensitive: false }
    

    before_create :check_params

    
    def self.from_omniauth(auth)
        where(email: auth.info.email).first_or_initialize do |user|
            user.email = auth.info.email
            user.name = auth.info.name
            user.password_digest = SecureRandom.hex
        end
    end

    def check_params
        self.email.downcase!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # before_action :set_current_user

    # def set_current_user
    #     if session[:user_id]
    #         Current.user = User.find_by(id: session[:user_id])
    #     end
    # end

end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
    def index
        @public_cards = Flashcard.public_card
        
        if params[:user_id]
            # @flashcards = User.find(params[:user_id]).flashcards
        else
            @flashcards = Flashcard.all
        end 
    end

    def users_flashcards
        if params[:user_id]
            @flashcards = User.find(params[:user_id]).flashcards.public_card
        end
    end

    def show
        @flashcard = Flashcard.find(params[:id])
    end

    def new
    
        @flashcard = Flashcard.new(user_id: params[:user_id])
        @subjects = Subject.all 
        @flashcardsubject = FlashcardSubject.new
        @status = ["public", "private"]
    
    end

    def create
        @flashcard = Flashcard.new(flashcard_params)

        if @flashcard.save 
            redirect_to flashcards_path
        else
            render 'new'
        end
    end

    def edit
        @flashcard = Flashcard.find(params[:id])
        @subjects = Subject.all
    end

    def update
        @flashcard = Flashcard.find(params[:id])
        @flashcard.update(flashcard_params)
        if @flashcard.save
            redirect_to flashcard_path(@flashcard)
        else
            render 'edit'
        end
    end

    def destroy
        Flashcard.destroy(params[:id])
        redirect_to flashcards_path
    end

    private

    def flashcard_params
        params.require(:flashcard).permit(
            :question,
             :answer, 
             :status,
             :flashcard,
             :id,
             :user_id,  
             flashcard_subjects_attributes: [:subject_id, :name, :id]
            )
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create 
        @user = User.find_by(email: params[:email].downcase)

        if !!@user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            redirect_to login_path
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path
    end

    def omniauth
        @user = User.from_omniauth(request.env['omniauth.auth'])
        
        if @user.save 
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :welcome
        end
    end

    def failure
        redirect_to root_path, alert: "Authentication failed, please try again."
    end

    def welcome

    end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

    def show
        @subject = Subject.find(params[:id])
    end

    def index
        if params[:user_flashcards]
            @subjects = Subject.find(params[:flashcard_id]).subjects
        end
    end

    def new
        @subject = Subject.new
    end

    def create
        @subject = Subject.new(subject_params)
        if @subject.save 
            redirect_to flashcards_path
        else
            render :new
        end
    end

    def subject_params
        params.require(:subject).permit(:name)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
    end

    def index
        if session[:user_id]
            @user = User.find(session[:user_id])
        end
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save 
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def edit
        @user = User.find(session[:user_id])
    end

    def update 
        @user = User.find(session[:user_id])
        @user.update(user_params)
        if @user.save
            redirect_to user_path(@user)
        else
            render 'edit'
        end
    end

    def destroy
        User.destroy(session[:user_id])
        redirect_to root_path
    end

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    # helper_method :current_user
    # helper_method :logged_in?

    def logged_in?
        !!session[:user_id]
    end
    
    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if !!session[:user_id]
    end
end

app/helpers/flashcards_helper.rb
module FlashcardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/flashcards/edit.html.erb
<h2>Edit Flashcard!</h2>
<%= form_for @flashcard do |f| %>
    <%= f.label :question %>
    <%= f.text_field :question %><br>

    <%= f.label :answer %>
    <%= f.text_field :answer %><br>

     <%= f.fields_for :flashcard_subjects, @flashcardsubject do |ff| %>
        <%= ff.label :subject_id, 'Select Subject: ' %>
        <%= ff.collection_select(:subject_id, @subjects, :id, :name) %><br>
        <% end %>

    <%= f.label :status, "Check to make post public" %>
    <%= f.check_box :status  %><br>

    <%= f.submit %>
<% end %>

app/views/flashcards/index.html.erb
<% if current_user %>
    <h1>All <%= current_user.name %>'s flashcards</h1> 

    <%= link_to "Home", user_path(current_user) %><br>
    <%= link_to "Create Subject", subject_path('new') %><br>
    <ul><% current_user.flashcards.each do |flashcard| %>
        <li>
            <h2><%= flashcard.question %><br>
            <%= link_to "Answer/View Card", flashcard_path(flashcard) %></h2>
        </li>
    </ul>
    <% end %>
<% else %>
        <h1>Available Flashcards</h1>
        <h3><%= link_to "Home Page", root_path %><br></h3>
        <h3><%= link_to 'Create Account and make your own flashcards and subjects!', user_path('new') %></h3><br>
        
        <% @public_cards.each do |flashcard| %>
    <ul>
        <li>
            <h2><%= flashcard.question %><br>
            <%= link_to "Answer/View Card", flashcard_path(flashcard) %></h2>
            <%= link_to "see all #{flashcard.user.name}'s public flashcards", user_users_flashcards_path(flashcard.user) %>
        </li>
    </ul>
    <% end %>
    
<% end %>

app/views/flashcards/new.html.erb
<h1>Make a new flashcard <%= current_user.name%> </h1> 
<%= link_to "Home", user_path(current_user) %><br>
<%= form_for @flashcard do |f| %>
    
    <% if @flashcard.errors.any? %>
        <div class="fields_with_errors">
        <h2>Errors:</h2>
        <ul>
            <% @flashcard.errors.full_messages.each do |message| %>
                <div><li><%= message %></li></div>
            <% end %>
        </ul>
    <% end %>

    <%= f.hidden_field :user_id %>

    <%= f.label :question %>
    <%= f.text_field :question %><br>

    <%= f.label :answer %>
    <%= f.text_field :answer %><br>

    <%= f.fields_for :flashcard_subjects, @flashcardsubject do |ff| %>
        <%= ff.label :subject_id, 'Select Subject: ' %>
        <%= ff.collection_select(:subject_id, @subjects, :id, :name) %><br>
        <% end %>
        
    <%= f.label :status, "Check to make post public" %>
    <%= f.check_box :status  %><br>

    <%= f.submit %>
<% end %>
<%= link_to "Show all flashcards", flashcards_path %>

app/views/flashcards/show.html.erb
<h1>Flashcard Question & Answer</h1>
<h4><% @flashcard.subjects.each do |s| %>
  <h4>Subject: <%= s.name %></h4>
<% end %></h4>
<h3>Question:<br></h3> <%= @flashcard.question %><br><br>
Answer:<br> <%= @flashcard.answer %><br><br>

<%= link_to "Back to Flashcards", flashcards_path %><br>
<% if current_user %>
  <%= link_to "Create Subject", subject_path('new') %><br>
  <%= link_to "Edit Card", edit_flashcard_path(@flashcard) %><br>
  <%= link_to "Delete", @flashcard, method: :delete, data: {confirm: "Are you sure you want to delete this card?"} %>
<% end %>

app/views/flashcards/users_flashcards.html.erb
<h1> Available Flashcards</h1>
<h3><%= link_to "Home Page", root_path %><br></h3>
<% @flashcards.each do |flashcard| %>
    <h5><%= flashcard.question %><br>
    <%= link_to "Answer/View Card", flashcard_path(flashcard) %></h2><br>
    </h5>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuizLot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/partials/_header.html.erb
<div>
    <h1>Hello</h1>
    <%= button_to "Login With Google", "/auth/google_oauth2", method: :post %><br>
</div>

app/views/subjects/index.html.erb
<% if current_user %>
    <h1>All <%= current_user.name %>'s flashcards</h1> 

    <%= link_to "Home", user_path(current_user) %><br>
    <%= link_to "Create Subject", subject_path('new') %><br>

    <ul><% current_user.flashcards.each do |flashcard| %>
        <li>
            <h2><%= flashcard.question %><br>
            <%= link_to "Answer/View Card", flashcard_path(flashcard) %></h2>
            <%= link_to subject.flashcard.name, flashcard_subjects_path(@subject.flashcard) %>
        </li>
    </ul>
    <% end %>
<% end %>

app/views/subjects/new.html.erb
<h1>Create New Subject</h1>
<h3><%= link_to "Home Page", root_path %><br></h3>

<%= form_for @subject do |f| %>

    <% if @subject.errors.any? %>
        <div class="fields with errors">
        <h2>Errors:</h2>
        <ul>
            <% @subject.errors.full_messages.each do |message| %>
                <div><li><%= message %></li></div>
            <% end %>
        </ul>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.submit %><br>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

    <% if @user.errors.any? %>
        <div class="fields with errors">
        <h2>Errors:</h2>
        <ul>
            <% @user.errors.full_messages.each do |message| %>
                <div><li><%= message %></li></div>
            <% end %>
        </ul>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.label :email %>
    <%= f.text_field :email %><br>
    
    <%= f.label :password  %>
    <%= f.password_field :password %><br>

    <%= f.label :password_confirmation  %>
    <%= f.password_field :password_confirmation %><br>

    <%= f.submit %><br>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Account</h1>
<h3><%= link_to "Home Page", user_path(@user) %><br></h3>

<%= form_for @user do |f| %>
   <%= render "form" %>
    <%= link_to 'delete account', current_user, method: :delete, data: { confirm: 'Are you certain you want to delete this?' } %>
<% end %>
    

app/views/users/new.html.erb
<h1>Create Category</h1>
<h3><%= link_to "Home", root_path %><br></h3>

<%= form_for @user do |f| %>
    <%= render 'form' %>
<% end %>
    

app/views/users/show.html.erb
<% if current_user %>
<h1>Welcome: <%= current_user.name %></h1><br> 

<%= link_to "Edit Account", edit_user_path(current_user) %><br>

<%= link_to "See your flashcards", flashcards_path %><br>

<%= link_to "Create Subject", subject_path('new') %><br>

<%= link_to "New flashcard", new_user_flashcard_path(@user) %><br>

<%= button_to "Logout", logout_path, method: "delete" %>
<% end %>